import React, { useRef } from 'react';
import { motion, useInView } from 'framer-motion';
import { ExternalLink, Search, BookOpen, Settings, Bot, Wrench, Shield, BarChart3, Zap, Users } from 'lucide-react';

const HelpCenterPage: React.FC = () => {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });

  const helpCategories = [
    {
      title: "Getting Started",
      icon: Zap,
      articles: [
        {
          title: "Quick Setup Guide",
          description: "Get RecomAI up and running in your Shopify store in under 5 minutes",
          url: "https://help.recomai.io/getting-started/quick-setup"
        },
        {
          title: "Installation & Integration",
          description: "Step-by-step guide to install RecomAI on your Shopify store",
          url: "https://help.recomai.io/getting-started/installation"
        },
        {
          title: "First Time Configuration",
          description: "Essential settings to configure when you first install RecomAI",
          url: "https://help.recomai.io/getting-started/first-configuration"
        }
      ]
    },
    {
      title: "Chatbot Management",
      icon: Bot,
      articles: [
        {
          title: "Chatbot Settings Overview",
          description: "Complete guide to all chatbot settings and customization options",
          url: "https://help.recomai.io/chatbot/settings-overview"
        },
        {
          title: "Training Your Chatbot",
          description: "How to train your AI chatbot to better understand your products and customers",
          url: "https://help.recomai.io/chatbot/training-guide"
        },
        {
          title: "Configuring Your Chatbot",
          description: "Advanced configuration options for personalizing your chatbot experience",
          url: "https://help.recomai.io/chatbot/configuration"
        },
        {
          title: "Chatbot Response Customization",
          description: "Customize chatbot responses to match your brand voice and tone",
          url: "https://help.recomai.io/chatbot/response-customization"
        }
      ]
    },
    {
      title: "Analytics & Reporting",
      icon: BarChart3,
      articles: [
        {
          title: "Understanding Your Dashboard",
          description: "Navigate and interpret your RecomAI analytics dashboard",
          url: "https://help.recomai.io/analytics/dashboard-guide"
        },
        {
          title: "Revenue Tracking",
          description: "Track revenue generated by AI recommendations",
          url: "https://help.recomai.io/analytics/revenue-tracking"
        },
        {
          title: "Performance Metrics",
          description: "Key metrics to monitor your recommendation engine performance",
          url: "https://help.recomai.io/analytics/performance-metrics"
        }
      ]
    },
    {
      title: "Advanced Settings",
      icon: Settings,
      articles: [
        {
          title: "Recommendation Algorithm Tuning",
          description: "Fine-tune your recommendation algorithms for better performance",
          url: "https://help.recomai.io/advanced/algorithm-tuning"
        },
        {
          title: "Custom CSS & Styling",
          description: "Customize the appearance of recommendation widgets",
          url: "https://help.recomai.io/advanced/custom-styling"
        },
        {
          title: "API Integration Guide",
          description: "Integrate RecomAI with external systems using our API",
          url: "https://help.recomai.io/advanced/api-integration"
        }
      ]
    },
    {
      title: "Account & Security",
      icon: Shield,
      articles: [
        {
          title: "Account Management",
          description: "Manage your RecomAI account settings and preferences",
          url: "https://help.recomai.io/account/management"
        },
        {
          title: "Security Best Practices",
          description: "Keep your RecomAI integration secure with these best practices",
          url: "https://help.recomai.io/account/security"
        },
        {
          title: "Data Privacy & GDPR",
          description: "Understanding data privacy and GDPR compliance with RecomAI",
          url: "https://help.recomai.io/account/privacy-gdpr"
        }
      ]
    },
    {
      title: "Team & Collaboration",
      icon: Users,
      articles: [
        {
          title: "User Roles & Permissions",
          description: "Manage team access and permissions in your RecomAI account",
          url: "https://help.recomai.io/team/roles-permissions"
        },
        {
          title: "Collaboration Features",
          description: "Work together with your team using RecomAI's collaboration tools",
          url: "https://help.recomai.io/team/collaboration"
        },
        {
          title: "Multi-Store Management",
          description: "Manage multiple Shopify stores from one RecomAI account",
          url: "https://help.recomai.io/team/multi-store"
        }
      ]
    }
  ];

  const handleArticleClick = (url: string) => {
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  return (
    <div ref={ref} className="pt-24 pb-16">
      {/* Hero Section */}
      <div className="bg-gradient-to-br from-blue-50 via-white to-purple-50 py-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8 }}
            className="text-center mb-16"
          >
            <div className="inline-flex items-center px-6 py-3 bg-gradient-to-r from-[#458cbb]/10 to-[#50b6d3]/10 rounded-full mb-6">
              <BookOpen className="w-5 h-5 text-[#458cbb] mr-2" />
              <span className="text-sm font-semibold text-gray-700">Help Center</span>
            </div>
            
            <h1 className="text-5xl lg:text-7xl font-bold text-gray-900 mb-6">
              Get{' '}
              <span className="bg-gradient-to-r from-[#458cbb] to-[#50b6d3] bg-clip-text text-transparent">
                Help
              </span>
            </h1>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed">
              Find comprehensive guides, tutorials, and documentation to help you get the most out of RecomAI. 
              From setup to advanced features, we've got you covered.
            </p>
          </motion.div>

          {/* Search Bar */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="max-w-2xl mx-auto mb-16"
          >
            <div className="relative">
              <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
              <input
                type="text"
                placeholder="Search help articles..."
                className="w-full pl-12 pr-4 py-4 bg-white rounded-2xl shadow-lg border border-gray-200 focus:ring-2 focus:ring-[#458cbb] focus:border-transparent transition-all duration-300 text-lg"
              />
            </div>
          </motion.div>
        </div>
      </div>

      {/* Help Categories */}
      <div className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="space-y-16">
            {helpCategories.map((category, categoryIndex) => (
              <motion.div
                key={categoryIndex}
                initial={{ opacity: 0, y: 50 }}
                animate={isInView ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.8, delay: categoryIndex * 0.1 }}
                className="space-y-8"
              >
                {/* Category Header */}
                <div className="flex items-center space-x-4 mb-8">
                  <div className="w-16 h-16 bg-gradient-to-r from-[#458cbb] to-[#50b6d3] rounded-2xl flex items-center justify-center shadow-lg">
                    <category.icon className="w-8 h-8 text-white" />
                  </div>
                  <div>
                    <h2 className="text-3xl font-bold text-gray-900">{category.title}</h2>
                    <div className="w-24 h-1 bg-gradient-to-r from-[#458cbb] to-[#50b6d3] rounded-full mt-2" />
                  </div>
                </div>

                {/* Articles Grid */}
                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {category.articles.map((article, articleIndex) => (
                    <motion.div
                      key={articleIndex}
                      initial={{ opacity: 0, y: 30 }}
                      animate={isInView ? { opacity: 1, y: 0 } : {}}
                      transition={{ duration: 0.6, delay: categoryIndex * 0.1 + articleIndex * 0.1 }}
                      whileHover={{ scale: 1.02, y: -5 }}
                      className="group cursor-pointer"
                      onClick={() => handleArticleClick(article.url)}
                    >
                      <div className="bg-white rounded-2xl p-6 shadow-lg border border-gray-200 hover:shadow-xl hover:border-[#458cbb]/30 transition-all duration-300 h-full">
                        <div className="flex items-start justify-between mb-4">
                          <h3 className="text-xl font-bold text-gray-900 group-hover:text-[#458cbb] transition-colors leading-tight">
                            {article.title}
                          </h3>
                          <ExternalLink className="w-5 h-5 text-gray-400 group-hover:text-[#458cbb] transition-colors flex-shrink-0 ml-2" />
                        </div>
                        
                        <p className="text-gray-600 leading-relaxed mb-4">
                          {article.description}
                        </p>

                        <div className="flex items-center text-[#458cbb] font-semibold text-sm group-hover:text-[#50b6d3] transition-colors">
                          <span>Read Article</span>
                          <motion.div
                            className="ml-2"
                            animate={{ x: [0, 4, 0] }}
                            transition={{ duration: 1.5, repeat: Infinity, ease: "easeInOut" }}
                          >
                            →
                          </motion.div>
                        </div>

                        {/* Hover gradient overlay */}
                        <motion.div
                          className="absolute inset-0 bg-gradient-to-r from-[#458cbb]/5 to-[#50b6d3]/5 rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none"
                        />
                      </div>
                    </motion.div>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>

      {/* Contact Support Section */}
      <div className="py-24 bg-gradient-to-r from-[#458cbb]/10 to-[#50b6d3]/10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8 }}
            className="space-y-8"
          >
            <h2 className="text-4xl font-bold text-gray-900">
              Can't Find What You're Looking For?
            </h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Our support team is here to help you succeed with RecomAI. Get personalized assistance from our experts.
            </p>
            <div className="flex flex-col sm:flex-row gap-6 justify-center">
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="px-8 py-4 bg-gradient-to-r from-[#458cbb] to-[#50b6d3] text-white font-semibold rounded-xl shadow-lg hover:shadow-xl transition-all duration-300"
                onClick={() => window.location.href = '/contact'}
              >
                Contact Support
              </motion.button>
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="px-8 py-4 border-2 border-[#458cbb]/30 text-[#458cbb] font-semibold rounded-xl hover:bg-[#458cbb]/5 transition-all duration-300"
                onClick={() => window.open('https://help.recomai.io/contact', '_blank')}
              >
                Live Chat
              </motion.button>
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
};

export default HelpCenterPage;